---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint
  options:
    config-data:
      ignore: venv

platforms:
  - name: redhat-8
    image: registry.access.redhat.com/ubi8/ubi

  - name: centos-8
    image: centos:8

  - name: redhat-7
    image: registry.access.redhat.com/ubi7/ubi

  - name: centos-7
    image: centos:7

  - name: centos-6
    image: centos:6

  - name: ubuntu-18.04
    image: ubuntu:18.04

  - name: ubuntu-19.04
    image: ubuntu:19.04

    # 9
  - name: debian-stretch
    image: debian:stretch

    # 10
  - name: debian-buster
    image: debian:buster

    # unstable
  - name: debian-sid
    image: debian:sid

provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["403"]

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
